"""Port for storing uploaded files. Implementations live in `knowvault.adapters.storage`."""

import re
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Protocol

# Keys are generated by the application (never from user input); this is a second line of
# defence against path traversal in any backend.
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*$")


class InvalidStorageKeyError(ValueError):
    pass


class StoredObjectNotFoundError(LookupError):
    pass


def validate_key(key: str) -> str:
    if not _KEY_PATTERN.match(key) or ".." in key.split("/"):
        raise InvalidStorageKeyError(key)
    return key


class ObjectStorage(Protocol):
    async def put_file(self, key: str, source: Path) -> None:
        """Stores the content of `source` under `key`, replacing any existing object."""
        ...

    async def read_bytes(self, key: str) -> bytes: ...

    def iter_chunks(self, key: str, chunk_size: int = 64 * 1024) -> AsyncIterator[bytes]: ...

    async def delete(self, key: str) -> None:
        """Removes the object. Deleting a missing object is not an error."""
        ...
